version: '3.9'
services:
  backend:
    container_name: backend
    build:
      ./backend
    ports:
      - 80:8080
    depends_on:
      - database
    environment:
      
    restart: always
  database:
    container_name: database
    image: postgis/postgis:15-3.3-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: poopstory
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw