version: '3.9'
services:
  proxy:
    image: nginx:1.23.4-alpine-slim
    container_name: proxy
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  frontend:
    container_name: frontend
    build:
      ./frontend/sample-01
    ports:
      - 3000:3000
      - 3001:3001
  backend:
    container_name: backend
    build:
      ./backend
    ports:
      - 8080:8080
      - 9000:9000
  database:
    container_name: postgres
    image: postgis/postgis:15-3.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: localdev
      POSTGRES_USER: poop
      POSTGRES_DB: poopstory
    volumes:
      - pg:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5080:5080
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: localdev
      PGADMIN_DISABLE_POSTFIX: "true"
      PGADMIN_LISTEN_PORT: 5080
    depends_on:
      - database

volumes:
  pg:
  pgadmin: